Aug-27 11:22:33.492 [main] DEBUG nextflow.cli.Launcher - $> nextflow run general_workflow.nf
Aug-27 11:22:33.683 [main] DEBUG nextflow.cli.CmdRun - N E X T F L O W  ~  version 24.04.4
Aug-27 11:22:33.711 [main] DEBUG nextflow.plugin.PluginsFacade - Setting up plugin manager > mode=prod; embedded=false; plugins-dir=/home/pestoup/.nextflow/plugins; core-plugins: nf-amazon@2.5.3,nf-azure@1.6.1,nf-cloudcache@0.4.1,nf-codecommit@0.2.1,nf-console@1.1.3,nf-ga4gh@1.3.0,nf-google@1.13.2-patch1,nf-tower@1.9.1,nf-wave@1.4.2-patch1
Aug-27 11:22:33.726 [main] INFO  o.pf4j.DefaultPluginStatusProvider - Enabled plugins: []
Aug-27 11:22:33.728 [main] INFO  o.pf4j.DefaultPluginStatusProvider - Disabled plugins: []
Aug-27 11:22:33.732 [main] INFO  org.pf4j.DefaultPluginManager - PF4J version 3.12.0 in 'deployment' mode
Aug-27 11:22:33.751 [main] INFO  org.pf4j.AbstractPluginManager - No plugins
Aug-27 11:22:33.782 [main] DEBUG nextflow.config.ConfigBuilder - Found config local: /home/pestoup/Documents/VIRUS_HOLOGREEN/Taxonomy/Gene_annotation/viral_marker_annotation/phylogeny2/nextflow.config
Aug-27 11:22:33.786 [main] DEBUG nextflow.config.ConfigBuilder - Parsing config file: /home/pestoup/Documents/VIRUS_HOLOGREEN/Taxonomy/Gene_annotation/viral_marker_annotation/phylogeny2/nextflow.config
Aug-27 11:22:33.829 [main] DEBUG n.secret.LocalSecretsProvider - Secrets store: /home/pestoup/.nextflow/secrets/store.json
Aug-27 11:22:33.834 [main] DEBUG nextflow.secret.SecretsLoader - Discovered secrets providers: [nextflow.secret.LocalSecretsProvider@644abb8f] - activable => nextflow.secret.LocalSecretsProvider@644abb8f
Aug-27 11:22:33.842 [main] DEBUG nextflow.config.ConfigBuilder - Applying config profile: `standard`
Aug-27 11:22:34.633 [main] DEBUG nextflow.cli.CmdRun - Applied DSL=2 from script declaration
Aug-27 11:22:34.659 [main] DEBUG nextflow.cli.CmdRun - Launching `general_workflow.nf` [grave_kay] DSL2 - revision: 38e25074be
Aug-27 11:22:34.661 [main] DEBUG nextflow.plugin.PluginsFacade - Plugins default=[]
Aug-27 11:22:34.661 [main] DEBUG nextflow.plugin.PluginsFacade - Plugins resolved requirement=[]
Aug-27 11:22:34.738 [main] DEBUG nextflow.Session - Session UUID: 12d9d9e8-474f-4e37-a36f-b11605f7f142
Aug-27 11:22:34.738 [main] DEBUG nextflow.Session - Run name: grave_kay
Aug-27 11:22:34.739 [main] DEBUG nextflow.Session - Executor pool size: 22
Aug-27 11:22:34.750 [main] DEBUG nextflow.file.FilePorter - File porter settings maxRetries=3; maxTransfers=50; pollTimeout=null
Aug-27 11:22:34.760 [main] DEBUG nextflow.util.ThreadPoolBuilder - Creating thread pool 'FileTransfer' minSize=10; maxSize=66; workQueue=LinkedBlockingQueue[10000]; allowCoreThreadTimeout=false
Aug-27 11:22:34.792 [main] DEBUG nextflow.cli.CmdRun - 
  Version: 24.04.4 build 5917
  Created: 01-08-2024 07:05 UTC (09:05 CEST)
  System: Linux 4.15.18-30-pve
  Runtime: Groovy 4.0.21 on OpenJDK 64-Bit Server VM 11.0.24+8-post-Ubuntu-1ubuntu320.04
  Encoding: UTF-8 (UTF-8)
  Process: 6040@bioinfo [195.221.212.102]
  CPUs: 22 - Mem: 244.5 GB (227.1 GB) - Swap: 16 GB (16 GB)
Aug-27 11:22:34.820 [main] DEBUG nextflow.Session - Work-dir: /home/pestoup/Documents/VIRUS_HOLOGREEN/Taxonomy/Gene_annotation/viral_marker_annotation/phylogeny2/logs/work [zfs]
Aug-27 11:22:34.821 [main] DEBUG nextflow.Session - Script base path does not exist or is not a directory: /home/pestoup/Documents/VIRUS_HOLOGREEN/Taxonomy/Gene_annotation/viral_marker_annotation/phylogeny2/bin
Aug-27 11:22:34.833 [main] DEBUG nextflow.executor.ExecutorFactory - Extension executors providers=[]
Aug-27 11:22:34.846 [main] DEBUG nextflow.Session - Observer factory: DefaultObserverFactory
Aug-27 11:22:34.915 [main] DEBUG nextflow.cache.CacheFactory - Using Nextflow cache factory: nextflow.cache.DefaultCacheFactory
Aug-27 11:22:34.929 [main] DEBUG nextflow.util.CustomThreadPool - Creating default thread pool > poolSize: 23; maxThreads: 1000
Aug-27 11:22:35.154 [main] DEBUG nextflow.Session - Session start
Aug-27 11:22:35.157 [main] DEBUG nextflow.trace.TraceFileObserver - Workflow started -- trace file: /home/pestoup/Documents/VIRUS_HOLOGREEN/Taxonomy/Gene_annotation/viral_marker_annotation/phylogeny2/logs/trace.txt
Aug-27 11:22:35.733 [main] DEBUG nextflow.script.ScriptRunner - > Launching execution
Aug-27 11:22:35.845 [main] DEBUG nextflow.executor.ExecutorFactory - << taskConfig executor: local
Aug-27 11:22:35.846 [main] DEBUG nextflow.executor.ExecutorFactory - >> processorType: 'local'
Aug-27 11:22:35.854 [main] DEBUG nextflow.executor.Executor - [warm up] executor > local
Aug-27 11:22:35.862 [main] DEBUG n.processor.LocalPollingMonitor - Creating local task monitor for executor 'local' > cpus=22; memory=244.5 GB; capacity=22; pollInterval=100ms; dumpInterval=5m
Aug-27 11:22:35.865 [main] DEBUG n.processor.TaskPollingMonitor - >>> barrier register (monitor: local)
Aug-27 11:22:35.979 [main] DEBUG nextflow.executor.ExecutorFactory - << taskConfig executor: local
Aug-27 11:22:35.980 [main] DEBUG nextflow.executor.ExecutorFactory - >> processorType: 'local'
Aug-27 11:22:35.988 [main] DEBUG nextflow.Session - Workflow process names [dsl2]: _6_tree, _2_dup_remove, _3_size_filter, _4_analysis, _1_filter_eval_refbounds, _5_alignment
Aug-27 11:22:35.988 [main] DEBUG nextflow.Session - Igniting dataflow network (2)
Aug-27 11:22:35.989 [main] DEBUG nextflow.processor.TaskProcessor - Starting process > _1_filter_eval_refbounds
Aug-27 11:22:35.991 [main] DEBUG nextflow.processor.TaskProcessor - Starting process > _2_dup_remove
Aug-27 11:22:35.992 [main] DEBUG nextflow.script.ScriptRunner - Parsed script files:
  Script_a29732319ab8da7b: /home/pestoup/Documents/VIRUS_HOLOGREEN/Taxonomy/Gene_annotation/viral_marker_annotation/phylogeny2/general_workflow.nf
Aug-27 11:22:35.992 [main] DEBUG nextflow.script.ScriptRunner - > Awaiting termination 
Aug-27 11:22:35.992 [main] DEBUG nextflow.Session - Session await
Aug-27 11:22:36.121 [Actor Thread 7] DEBUG nextflow.conda.CondaCache - conda found local env for environment=bioconda::mmseqs2 conda-forge::pandas conda-forge::matplotlib conda-forge::seaborn conda-forge::biopython; path=/home/pestoup/Documents/VIRUS_HOLOGREEN/Taxonomy/Gene_annotation/viral_marker_annotation/phylogeny2/logs/work/conda/env-0742acb7b66447a7f9ad1677c8e7d116
Aug-27 11:22:36.239 [Task submitter] DEBUG n.executor.local.LocalTaskHandler - Launch cmd line: /bin/bash -ue .command.run
Aug-27 11:22:36.243 [Task submitter] INFO  nextflow.Session - [c7/3559c3] Submitted process > _1_filter_eval_refbounds
Aug-27 11:22:57.343 [Task monitor] DEBUG n.processor.TaskPollingMonitor - Task completed > TaskHandler[id: 1; name: _1_filter_eval_refbounds; status: COMPLETED; exit: 1; error: -; workDir: /home/pestoup/Documents/VIRUS_HOLOGREEN/Taxonomy/Gene_annotation/viral_marker_annotation/phylogeny2/logs/work/c7/3559c3a809a784fe3decc0e12857cf]
Aug-27 11:22:57.344 [Task monitor] DEBUG nextflow.util.ThreadPoolBuilder - Creating thread pool 'TaskFinalizer' minSize=10; maxSize=66; workQueue=LinkedBlockingQueue[10000]; allowCoreThreadTimeout=false
Aug-27 11:22:57.354 [TaskFinalizer-1] DEBUG nextflow.processor.TaskProcessor - Handling unexpected condition for
  task: name=_1_filter_eval_refbounds; work-dir=/home/pestoup/Documents/VIRUS_HOLOGREEN/Taxonomy/Gene_annotation/viral_marker_annotation/phylogeny2/logs/work/c7/3559c3a809a784fe3decc0e12857cf
  error [nextflow.exception.ProcessFailedException]: Process `_1_filter_eval_refbounds` terminated with an error exit status (1)
Aug-27 11:22:57.391 [TaskFinalizer-1] ERROR nextflow.processor.TaskProcessor - Error executing process > '_1_filter_eval_refbounds'

Caused by:
  Process `_1_filter_eval_refbounds` terminated with an error exit status (1)


Command executed:

  #Setup out folder    
     mkdir -p /home/pestoup/Documents/VIRUS_HOLOGREEN/Taxonomy/Gene_annotation/viral_marker_annotation/phylogeny2/out/STEP_1
     mkdir -p /home/pestoup/Documents/VIRUS_HOLOGREEN/Taxonomy/Gene_annotation/viral_marker_annotation/phylogeny2/out/STEP_1/score_filtration/filt_results/score_filt
  
     #Filtration by evalue score in alignments
     python /home/pestoup/Documents/VIRUS_HOLOGREEN/Taxonomy/Gene_annotation/viral_marker_annotation/phylogeny2/scripts/STEP1A_filt_eval.py /home/pestoup/Documents/VIRUS_HOLOGREEN/Taxonomy/Gene_annotation/viral_marker_annotation/phylogeny2/data/alignments /home/pestoup/Documents/VIRUS_HOLOGREEN/Taxonomy/Gene_annotation/viral_marker_annotation/phylogeny2/out/STEP_1/score_filtration/filt_results "1e-0,1e-5,1e-10,1e-20,1e-50,1e-75,1e-100,1e-150,1e-200"
         #Log
  echo "log_1: filtration of ORF by evalue : completed" >> "/home/pestoup/Documents/VIRUS_HOLOGREEN/Taxonomy/Gene_annotation/viral_marker_annotation/phylogeny2/logs/log_STEP1"
  
     #Determine the score bounds of alignment for each marker gene
     python  /home/pestoup/Documents/VIRUS_HOLOGREEN/Taxonomy/Gene_annotation/viral_marker_annotation/phylogeny2/scripts/STEP1B_define_bounds.py /home/pestoup/Documents/VIRUS_HOLOGREEN/Taxonomy/Gene_annotation/viral_marker_annotation/phylogeny2/data/seq_references /home/pestoup/Documents/VIRUS_HOLOGREEN/Taxonomy/Gene_annotation/viral_marker_annotation/phylogeny2/out/STEP_1/score_filtration/ref_db /home/pestoup/Documents/VIRUS_HOLOGREEN/Taxonomy/Gene_annotation/viral_marker_annotation/phylogeny2/out/STEP_1/score_filtration/bounds_alignment /home/pestoup/Documents/VIRUS_HOLOGREEN/Taxonomy/Gene_annotation/viral_marker_annotation/phylogeny2/out/STEP_1/score_filtration/bounds_results /home/pestoup/Documents/VIRUS_HOLOGREEN/Taxonomy/Gene_annotation/viral_marker_annotation/phylogeny2/out/STEP_1/score_filtration/bounds_alignment_temp
         #Log
         echo "log_1: determined bounds of ref : completed" >> "/home/pestoup/Documents/VIRUS_HOLOGREEN/Taxonomy/Gene_annotation/viral_marker_annotation/phylogeny2/logs/log_STEP1"
  
     #Filter by the right bounds threashold for ORF
     python /home/pestoup/Documents/VIRUS_HOLOGREEN/Taxonomy/Gene_annotation/viral_marker_annotation/phylogeny2/scripts/STEP1C_filter_by_ref_score.py /home/pestoup/Documents/VIRUS_HOLOGREEN/Taxonomy/Gene_annotation/viral_marker_annotation/phylogeny2/out/STEP_1/score_filtration/bounds_results /home/pestoup/Documents/VIRUS_HOLOGREEN/Taxonomy/Gene_annotation/viral_marker_annotation/phylogeny2/data/alignments /home/pestoup/Documents/VIRUS_HOLOGREEN/Taxonomy/Gene_annotation/viral_marker_annotation/phylogeny2/out/STEP_1/score_filtration/score_aln_filt /home/pestoup/Documents/VIRUS_HOLOGREEN/Taxonomy/Gene_annotation/viral_marker_annotation/phylogeny2/out/STEP_1/score_filtration/filt_results/score_filt /home/pestoup/Documents/VIRUS_HOLOGREEN/Taxonomy/Gene_annotation/viral_marker_annotation/phylogeny2/data/orf_codants /home/pestoup/Documents/VIRUS_HOLOGREEN/Taxonomy/Gene_annotation/viral_marker_annotation/phylogeny2/out/STEP_1/score_filtration/orf_codants_score /home/pestoup/Documents/VIRUS_HOLOGREEN/Taxonomy/Gene_annotation/viral_marker_annotation/phylogeny2/out/STEP_1/score_filtration/bounds_summary
         #Log
  echo "log_1: filtration of ORF by socre bounds : completed" >> "/home/pestoup/Documents/VIRUS_HOLOGREEN/Taxonomy/Gene_annotation/viral_marker_annotation/phylogeny2/logs/log_STEP1"
  
     #Filtration step analysis 
     mkdir -p /home/pestoup/Documents/VIRUS_HOLOGREEN/Taxonomy/Gene_annotation/viral_marker_annotation/phylogeny2/out/log_analysis/bounds_performance
     python /home/pestoup/Documents/VIRUS_HOLOGREEN/Taxonomy/Gene_annotation/viral_marker_annotation/phylogeny2/scripts/STEP1D_analyze_eval_bounds.py /home/pestoup/Documents/VIRUS_HOLOGREEN/Taxonomy/Gene_annotation/viral_marker_annotation/phylogeny2/out/STEP_1/score_filtration/filt_results /home/pestoup/Documents/VIRUS_HOLOGREEN/Taxonomy/Gene_annotation/viral_marker_annotation/phylogeny2/out/log_analysis/bounds_performance /home/pestoup/Documents/VIRUS_HOLOGREEN/Taxonomy/Gene_annotation/viral_marker_annotation/phylogeny2/data/orf_codants /home/pestoup/Documents/VIRUS_HOLOGREEN/Taxonomy/Gene_annotation/viral_marker_annotation/phylogeny2/out/STEP_1/score_filtration/orf_codants_score
  
     #Log
     echo "log_1: Analysis of different filtration step : completed" >> "/home/pestoup/Documents/VIRUS_HOLOGREEN/Taxonomy/Gene_annotation/viral_marker_annotation/phylogeny2/logs/log_STEP1"
     echo "log_1" > log_1

Command exit status:
  1

Command output:
  
  Time for processing: 0h 0m 0s 0ms
  ==================================================] 55 4s 979ms
  Time for merging to result: 0h 0m 0s 0ms
  2989 alignments calculated
  2989 sequence pairs passed the thresholds (1.000000 of overall calculated)
  54.345455 hits per query sequence
  Time for processing: 0h 0m 5s 290ms
  rmdb /home/pestoup/Documents/VIRUS_HOLOGREEN/Taxonomy/Gene_annotation/viral_marker_annotation/phylogeny2/out/STEP_1/score_filtration/bounds_alignment_temp/rnapol1/3204290293984669307/search_tmp/10810056582306941977/pref_0 -v 3 
  
  Time for processing: 0h 0m 0s 0ms
  rmdb /home/pestoup/Documents/VIRUS_HOLOGREEN/Taxonomy/Gene_annotation/viral_marker_annotation/phylogeny2/out/STEP_1/score_filtration/bounds_alignment_temp/rnapol1/3204290293984669307/search_tmp/10810056582306941977/aln_0 -v 3 
  
  Time for processing: 0h 0m 0s 0ms
  rmdb /home/pestoup/Documents/VIRUS_HOLOGREEN/Taxonomy/Gene_annotation/viral_marker_annotation/phylogeny2/out/STEP_1/score_filtration/bounds_alignment_temp/rnapol1/3204290293984669307/search_tmp/10810056582306941977/input_0 -v 3 
  
  Time for processing: 0h 0m 0s 0ms
  rmdb /home/pestoup/Documents/VIRUS_HOLOGREEN/Taxonomy/Gene_annotation/viral_marker_annotation/phylogeny2/out/STEP_1/score_filtration/bounds_alignment_temp/rnapol1/3204290293984669307/search_tmp/10810056582306941977/aln_merge -v 3 
  
  Time for processing: 0h 0m 0s 0ms
  convertalis /home/pestoup/Documents/VIRUS_HOLOGREEN/Taxonomy/Gene_annotation/viral_marker_annotation/phylogeny2/out/STEP_1/score_filtration/bounds_alignment_temp/rnapol1/3204290293984669307/query /home/pestoup/Documents/VIRUS_HOLOGREEN/Taxonomy/Gene_annotation/viral_marker_annotation/phylogeny2/out/STEP_1/score_filtration/ref_db/rnapol1 /home/pestoup/Documents/VIRUS_HOLOGREEN/Taxonomy/Gene_annotation/viral_marker_annotation/phylogeny2/out/STEP_1/score_filtration/bounds_alignment_temp/rnapol1/3204290293984669307/result /home/pestoup/Documents/VIRUS_HOLOGREEN/Taxonomy/Gene_annotation/viral_marker_annotation/phylogeny2/out/STEP_1/score_filtration/bounds_alignment/rnapol1 --sub-mat 'aa:blosum62.out,nucl:nucleotide.out' --format-mode 0 --format-output query,target,pident,alnlen,mismatch,gapopen,qstart,qend,tstart,tend,evalue,bits --translation-table 1 --gap-open aa:11,nucl:5 --gap-extend aa:1,nucl:2 --db-output 0 --db-load-mode 0 --search-type 0 --threads 4 --compressed 0 -v 3 
  
  [=================================================================] 55 0s 3ms
  Time for merging to rnapol1: 0h 0m 0s 0ms
  Time for processing: 0h 0m 0s 7ms
  rmdb /home/pestoup/Documents/VIRUS_HOLOGREEN/Taxonomy/Gene_annotation/viral_marker_annotation/phylogeny2/out/STEP_1/score_filtration/bounds_alignment_temp/rnapol1/3204290293984669307/result -v 3 
  
  Time for processing: 0h 0m 0s 0ms
  rmdb /home/pestoup/Documents/VIRUS_HOLOGREEN/Taxonomy/Gene_annotation/viral_marker_annotation/phylogeny2/out/STEP_1/score_filtration/bounds_alignment_temp/rnapol1/3204290293984669307/query -v 3 
  
  Time for processing: 0h 0m 0s 0ms
  rmdb /home/pestoup/Documents/VIRUS_HOLOGREEN/Taxonomy/Gene_annotation/viral_marker_annotation/phylogeny2/out/STEP_1/score_filtration/bounds_alignment_temp/rnapol1/3204290293984669307/query_h -v 3 
  
  Time for processing: 0h 0m 0s 0ms
  
  Répertoire déjà existant : /home/pestoup/Documents/VIRUS_HOLOGREEN/Taxonomy/Gene_annotation/viral_marker_annotation/phylogeny2/out/STEP_1/score_filtration/bounds_alignment
  Répertoire déjà existant : /home/pestoup/Documents/VIRUS_HOLOGREEN/Taxonomy/Gene_annotation/viral_marker_annotation/phylogeny2/out/STEP_1/score_filtration/bounds_alignment_temp
  Erreur lors de la recherche MMseqs2 pour /home/pestoup/Documents/VIRUS_HOLOGREEN/Taxonomy/Gene_annotation/viral_marker_annotation/phylogeny2/data/seq_references/rnapol2.prt: Command 'mmseqs easy-search /home/pestoup/Documents/VIRUS_HOLOGREEN/Taxonomy/Gene_annotation/viral_marker_annotation/phylogeny2/data/seq_references/rnapol2.prt /home/pestoup/Documents/VIRUS_HOLOGREEN/Taxonomy/Gene_annotation/viral_marker_annotation/phylogeny2/out/STEP_1/score_filtration/ref_db/rnapol2 /home/pestoup/Documents/VIRUS_HOLOGREEN/Taxonomy/Gene_annotation/viral_marker_annotation/phylogeny2/out/STEP_1/score_filtration/bounds_alignment/rnapol2 /home/pestoup/Documents/VIRUS_HOLOGREEN/Taxonomy/Gene_annotation/viral_marker_annotation/phylogeny2/out/STEP_1/score_filtration/bounds_alignment_temp/rnapol2 --format-output query,target,pident,alnlen,mismatch,gapopen,qstart,qend,tstart,tend,evalue,bits --threads 4' returned non-zero exit status 1.
  Erreur lors de l'extraction des scores du fichier /home/pestoup/Documents/VIRUS_HOLOGREEN/Taxonomy/Gene_annotation/viral_marker_annotation/phylogeny2/out/STEP_1/score_filtration/bounds_alignment/rnapol2: [Errno 2] No such file or directory: '/home/pestoup/Documents/VIRUS_HOLOGREEN/Taxonomy/Gene_annotation/viral_marker_annotation/phylogeny2/out/STEP_1/score_filtration/bounds_alignment/rnapol2'
  Répertoire déjà existant : /home/pestoup/Documents/VIRUS_HOLOGREEN/Taxonomy/Gene_annotation/viral_marker_annotation/phylogeny2/out/STEP_1/score_filtration/bounds_results
  Scores enregistrés dans /home/pestoup/Documents/VIRUS_HOLOGREEN/Taxonomy/Gene_annotation/viral_marker_annotation/phylogeny2/out/STEP_1/score_filtration/bounds_results/rnapol2_worst_scores.txt
  Recherche terminée pour /home/pestoup/Documents/VIRUS_HOLOGREEN/Taxonomy/Gene_annotation/viral_marker_annotation/phylogeny2/data/seq_references/vltf3.prt
  Répertoire déjà existant : /home/pestoup/Documents/VIRUS_HOLOGREEN/Taxonomy/Gene_annotation/viral_marker_annotation/phylogeny2/out/STEP_1/score_filtration/bounds_results
  Scores enregistrés dans /home/pestoup/Documents/VIRUS_HOLOGREEN/Taxonomy/Gene_annotation/viral_marker_annotation/phylogeny2/out/STEP_1/score_filtration/bounds_results/vltf3_worst_scores.txt
  Recherche terminée pour /home/pestoup/Documents/VIRUS_HOLOGREEN/Taxonomy/Gene_annotation/viral_marker_annotation/phylogeny2/data/seq_references/dnapol.prt
  Répertoire déjà existant : /home/pestoup/Documents/VIRUS_HOLOGREEN/Taxonomy/Gene_annotation/viral_marker_annotation/phylogeny2/out/STEP_1/score_filtration/bounds_results
  Scores enregistrés dans /home/pestoup/Documents/VIRUS_HOLOGREEN/Taxonomy/Gene_annotation/viral_marker_annotation/phylogeny2/out/STEP_1/score_filtration/bounds_results/dnapol_worst_scores.txt
  Recherche terminée pour /home/pestoup/Documents/VIRUS_HOLOGREEN/Taxonomy/Gene_annotation/viral_marker_annotation/phylogeny2/data/seq_references/rnapol1.prt
  Répertoire déjà existant : /home/pestoup/Documents/VIRUS_HOLOGREEN/Taxonomy/Gene_annotation/viral_marker_annotation/phylogeny2/out/STEP_1/score_filtration/bounds_results
  Scores enregistrés dans /home/pestoup/Documents/VIRUS_HOLOGREEN/Taxonomy/Gene_annotation/viral_marker_annotation/phylogeny2/out/STEP_1/score_filtration/bounds_results/rnapol1_worst_scores.txt

Command error:
  
  Time for processing: 0h 0m 0s 0ms
  rmdb /home/pestoup/Documents/VIRUS_HOLOGREEN/Taxonomy/Gene_annotation/viral_marker_annotation/phylogeny2/out/STEP_1/score_filtration/bounds_alignment_temp/rnapol1/3204290293984669307/query -v 3 
  
  Time for processing: 0h 0m 0s 0ms
  rmdb /home/pestoup/Documents/VIRUS_HOLOGREEN/Taxonomy/Gene_annotation/viral_marker_annotation/phylogeny2/out/STEP_1/score_filtration/bounds_alignment_temp/rnapol1/3204290293984669307/query_h -v 3 
  
  Time for processing: 0h 0m 0s 0ms
  
  Répertoire déjà existant : /home/pestoup/Documents/VIRUS_HOLOGREEN/Taxonomy/Gene_annotation/viral_marker_annotation/phylogeny2/out/STEP_1/score_filtration/bounds_alignment
  Répertoire déjà existant : /home/pestoup/Documents/VIRUS_HOLOGREEN/Taxonomy/Gene_annotation/viral_marker_annotation/phylogeny2/out/STEP_1/score_filtration/bounds_alignment_temp
  Erreur lors de la recherche MMseqs2 pour /home/pestoup/Documents/VIRUS_HOLOGREEN/Taxonomy/Gene_annotation/viral_marker_annotation/phylogeny2/data/seq_references/rnapol2.prt: Command 'mmseqs easy-search /home/pestoup/Documents/VIRUS_HOLOGREEN/Taxonomy/Gene_annotation/viral_marker_annotation/phylogeny2/data/seq_references/rnapol2.prt /home/pestoup/Documents/VIRUS_HOLOGREEN/Taxonomy/Gene_annotation/viral_marker_annotation/phylogeny2/out/STEP_1/score_filtration/ref_db/rnapol2 /home/pestoup/Documents/VIRUS_HOLOGREEN/Taxonomy/Gene_annotation/viral_marker_annotation/phylogeny2/out/STEP_1/score_filtration/bounds_alignment/rnapol2 /home/pestoup/Documents/VIRUS_HOLOGREEN/Taxonomy/Gene_annotation/viral_marker_annotation/phylogeny2/out/STEP_1/score_filtration/bounds_alignment_temp/rnapol2 --format-output query,target,pident,alnlen,mismatch,gapopen,qstart,qend,tstart,tend,evalue,bits --threads 4' returned non-zero exit status 1.
  Erreur lors de l'extraction des scores du fichier /home/pestoup/Documents/VIRUS_HOLOGREEN/Taxonomy/Gene_annotation/viral_marker_annotation/phylogeny2/out/STEP_1/score_filtration/bounds_alignment/rnapol2: [Errno 2] No such file or directory: '/home/pestoup/Documents/VIRUS_HOLOGREEN/Taxonomy/Gene_annotation/viral_marker_annotation/phylogeny2/out/STEP_1/score_filtration/bounds_alignment/rnapol2'
  Répertoire déjà existant : /home/pestoup/Documents/VIRUS_HOLOGREEN/Taxonomy/Gene_annotation/viral_marker_annotation/phylogeny2/out/STEP_1/score_filtration/bounds_results
  Scores enregistrés dans /home/pestoup/Documents/VIRUS_HOLOGREEN/Taxonomy/Gene_annotation/viral_marker_annotation/phylogeny2/out/STEP_1/score_filtration/bounds_results/rnapol2_worst_scores.txt
  Recherche terminée pour /home/pestoup/Documents/VIRUS_HOLOGREEN/Taxonomy/Gene_annotation/viral_marker_annotation/phylogeny2/data/seq_references/vltf3.prt
  Répertoire déjà existant : /home/pestoup/Documents/VIRUS_HOLOGREEN/Taxonomy/Gene_annotation/viral_marker_annotation/phylogeny2/out/STEP_1/score_filtration/bounds_results
  Scores enregistrés dans /home/pestoup/Documents/VIRUS_HOLOGREEN/Taxonomy/Gene_annotation/viral_marker_annotation/phylogeny2/out/STEP_1/score_filtration/bounds_results/vltf3_worst_scores.txt
  Recherche terminée pour /home/pestoup/Documents/VIRUS_HOLOGREEN/Taxonomy/Gene_annotation/viral_marker_annotation/phylogeny2/data/seq_references/dnapol.prt
  Répertoire déjà existant : /home/pestoup/Documents/VIRUS_HOLOGREEN/Taxonomy/Gene_annotation/viral_marker_annotation/phylogeny2/out/STEP_1/score_filtration/bounds_results
  Scores enregistrés dans /home/pestoup/Documents/VIRUS_HOLOGREEN/Taxonomy/Gene_annotation/viral_marker_annotation/phylogeny2/out/STEP_1/score_filtration/bounds_results/dnapol_worst_scores.txt
  Recherche terminée pour /home/pestoup/Documents/VIRUS_HOLOGREEN/Taxonomy/Gene_annotation/viral_marker_annotation/phylogeny2/data/seq_references/rnapol1.prt
  Répertoire déjà existant : /home/pestoup/Documents/VIRUS_HOLOGREEN/Taxonomy/Gene_annotation/viral_marker_annotation/phylogeny2/out/STEP_1/score_filtration/bounds_results
  Scores enregistrés dans /home/pestoup/Documents/VIRUS_HOLOGREEN/Taxonomy/Gene_annotation/viral_marker_annotation/phylogeny2/out/STEP_1/score_filtration/bounds_results/rnapol1_worst_scores.txt
  Traceback (most recent call last):
    File "/home/pestoup/Documents/VIRUS_HOLOGREEN/Taxonomy/Gene_annotation/viral_marker_annotation/phylogeny2/scripts/STEP1C_filter_by_ref_score.py", line 87, in <module>
      main()
    File "/home/pestoup/Documents/VIRUS_HOLOGREEN/Taxonomy/Gene_annotation/viral_marker_annotation/phylogeny2/scripts/STEP1C_filter_by_ref_score.py", line 80, in main
      worst_scores = read_worst_scores(worst_scores_folder)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/home/pestoup/Documents/VIRUS_HOLOGREEN/Taxonomy/Gene_annotation/viral_marker_annotation/phylogeny2/scripts/STEP1C_filter_by_ref_score.py", line 9, in read_worst_scores
      df = pd.read_csv(file, sep="\t", header=None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/home/pestoup/Documents/VIRUS_HOLOGREEN/Taxonomy/Gene_annotation/viral_marker_annotation/phylogeny2/logs/work/conda/env-0742acb7b66447a7f9ad1677c8e7d116/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1026, in read_csv
      return _read(filepath_or_buffer, kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/home/pestoup/Documents/VIRUS_HOLOGREEN/Taxonomy/Gene_annotation/viral_marker_annotation/phylogeny2/logs/work/conda/env-0742acb7b66447a7f9ad1677c8e7d116/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 620, in _read
      parser = TextFileReader(filepath_or_buffer, **kwds)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/home/pestoup/Documents/VIRUS_HOLOGREEN/Taxonomy/Gene_annotation/viral_marker_annotation/phylogeny2/logs/work/conda/env-0742acb7b66447a7f9ad1677c8e7d116/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1620, in __init__
      self._engine = self._make_engine(f, self.engine)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/home/pestoup/Documents/VIRUS_HOLOGREEN/Taxonomy/Gene_annotation/viral_marker_annotation/phylogeny2/logs/work/conda/env-0742acb7b66447a7f9ad1677c8e7d116/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1898, in _make_engine
      return mapping[engine](f, **self.options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/home/pestoup/Documents/VIRUS_HOLOGREEN/Taxonomy/Gene_annotation/viral_marker_annotation/phylogeny2/logs/work/conda/env-0742acb7b66447a7f9ad1677c8e7d116/lib/python3.12/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 93, in __init__
      self._reader = parsers.TextReader(src, **kwds)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "parsers.pyx", line 581, in pandas._libs.parsers.TextReader.__cinit__
  pandas.errors.EmptyDataError: No columns to parse from file

Work dir:
  /home/pestoup/Documents/VIRUS_HOLOGREEN/Taxonomy/Gene_annotation/viral_marker_annotation/phylogeny2/logs/work/c7/3559c3a809a784fe3decc0e12857cf

Tip: when you have fixed the problem you can continue the execution adding the option `-resume` to the run command line
Aug-27 11:22:57.401 [main] DEBUG nextflow.Session - Session await > all processes finished
Aug-27 11:22:57.411 [Task monitor] DEBUG n.processor.TaskPollingMonitor - <<< barrier arrives (monitor: local) - terminating tasks monitor poll loop
Aug-27 11:22:57.412 [main] DEBUG nextflow.Session - Session await > all barriers passed
Aug-27 11:22:57.436 [TaskFinalizer-1] DEBUG nextflow.Session - Session aborted -- Cause: Process `_1_filter_eval_refbounds` terminated with an error exit status (1)
Aug-27 11:22:57.464 [main] DEBUG nextflow.util.ThreadPoolManager - Thread pool 'TaskFinalizer' shutdown completed (hard=false)
Aug-27 11:22:57.472 [main] DEBUG n.trace.WorkflowStatsObserver - Workflow completed > WorkflowStats[succeededCount=0; failedCount=1; ignoredCount=0; cachedCount=0; pendingCount=0; submittedCount=0; runningCount=0; retriesCount=0; abortedCount=0; succeedDuration=0ms; failedDuration=5m 16s; cachedDuration=0ms;loadCpus=0; loadMemory=0; peakRunning=1; peakCpus=15; peakMemory=47 GB; ]
Aug-27 11:22:57.472 [main] DEBUG nextflow.trace.TraceFileObserver - Workflow completed -- saving trace file
Aug-27 11:22:57.474 [main] DEBUG nextflow.trace.ReportObserver - Workflow completed -- rendering execution report
Aug-27 11:22:58.277 [main] DEBUG nextflow.trace.TimelineObserver - Workflow completed -- rendering execution timeline
Aug-27 11:22:58.368 [main] DEBUG nextflow.cache.CacheDB - Closing CacheDB done
Aug-27 11:22:58.393 [main] DEBUG nextflow.script.ScriptRunner - > Execution complete -- Goodbye
